source "https://rubygems.org"

ruby "3.2.10"

gem "rails", "~> 7.1"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

# Auth
gem "devise"
gem "devise-jwt"

# CORS — allow React frontend to call this API
gem "rack-cors"

# Image processing for Active Storage
gem "image_processing", "~> 1.2"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "rspec-rails"
  gem "factory_bot_rails"
end
